# Generated by Django 5.1.1 on 2025-04-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasificacion_peso', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasificacion',
            options={'verbose_name': 'CLASIFICACION DE PESO', 'verbose_name_plural': 'CLASIFICACION DE PESO'},
        ),
        migrations.AlterField(
            model_name='clasificacion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='clasificacion',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='clasificacion',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre de la clasificación'),
        ),
    ]
