# Generated by Django 5.1.1 on 2025-04-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida_diaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comida_diaria',
            options={'verbose_name': 'CONSUMO DE COMIDA DIARIA', 'verbose_name_plural': 'CONSUMO DE COMIDA DIARIA'},
        ),
        migrations.AlterField(
            model_name='comida_diaria',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='comida_diaria',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='comida_diaria',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Cantidad de comida diaria'),
        ),
    ]
