# Generated by Django 5.1.1 on 2025-04-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades_fisicas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadesFisicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la actividad')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'ACTIVIDAD FÍSICA',
                'verbose_name_plural': 'ACTIVIDADES FÍSICAS',
            },
        ),
    ]
