# Generated by Django 5.1.1 on 2025-04-13 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades_fisicas', '0002_actividadesfisicas'),
        ('personas', '0004_alter_personas_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='actividades_fisicas',
        ),
    ]
