# Generated by Django 5.1.1 on 2025-04-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estres_ansiedad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estres_ansiedad',
            options={'verbose_name': 'ESTRES O ANSIEDAD', 'verbose_name_plural': 'ESTRES O ANSIEDAD'},
        ),
        migrations.AlterField(
            model_name='estres_ansiedad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='estres_ansiedad',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='estres_ansiedad',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Sufre de estres o ansiedad'),
        ),
    ]
