# Generated by Django 5.1.1 on 2025-04-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estres_ansiedad', '0002_alter_estres_ansiedad_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estres_ansiedad',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Sufre de estres o ansiedad?'),
        ),
    ]
