# Generated by Django 5.1.1 on 2025-04-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antecedentes_familiares', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antecedentes_familiares',
            options={'verbose_name': 'ANTECEDENTES FAMILIARES', 'verbose_name_plural': 'ANTECEDENTES FAMILIARES'},
        ),
        migrations.AlterField(
            model_name='antecedentes_familiares',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='antecedentes_familiares',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='antecedentes_familiares',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Tiene antecedentes familiares de obesidad'),
        ),
    ]
