# Generated by Django 5.1.1 on 2025-04-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antecedentes_familiares', '0002_alter_antecedentes_familiares_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedentes_familiares',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Tiene antecedentes familiares de obesidad?'),
        ),
    ]
