# Generated by Django 5.1.1 on 2025-04-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumo_medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumo_medicamentos',
            options={'verbose_name': 'CONSUMO DE MEDICAMENTOS', 'verbose_name_plural': 'CONSUMO DE MEDICAMENTOS'},
        ),
        migrations.AlterField(
            model_name='consumo_medicamentos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='consumo_medicamentos',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='consumo_medicamentos',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Consume medicamentos'),
        ),
    ]
