# Generated by Django 5.1.1 on 2025-04-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumo_medicamentos', '0002_alter_consumo_medicamentos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo_medicamentos',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Consume medicamentos?'),
        ),
    ]
