# Generated by Django 5.1.1 on 2025-04-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumo_comida_rapida', '0002_alter_consumo_comida_rapida_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumo_comida_rapida',
            options={'verbose_name': 'CONSUMO DE COMIDA RAPIDA', 'verbose_name_plural': 'CONSUMO DE COMIDA RAPIDA'},
        ),
        migrations.AlterField(
            model_name='consumo_comida_rapida',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Consume comida rapida?'),
        ),
    ]
