# Generated by Django 5.1.1 on 2025-04-13 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genero', '0002_alter_genero_created_at_alter_genero_is_delete_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genero',
            options={'verbose_name': 'GÉNEROS', 'verbose_name_plural': 'GÉNEROS'},
        ),
    ]
