# Generated by Django 5.1.1 on 2025-04-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condiciones_medicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condiciones_medicas',
            options={'verbose_name': 'CONDICION MEDICA', 'verbose_name_plural': 'CONDICION MEDICA'},
        ),
        migrations.AlterField(
            model_name='condiciones_medicas',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='condiciones_medicas',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='condiciones_medicas',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre de la condición'),
        ),
    ]
