# Generated by Django 5.1.1 on 2025-04-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condiciones_medicas', '0002_alter_condiciones_medicas_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condiciones_medicas',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Tiene condiciones médicas de obesidad?'),
        ),
    ]
