# Generated by Django 5.1.1 on 2025-03-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='genero',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
