# Generated by Django 5.1.1 on 2025-04-13 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades_fisicas', '0001_initial'),
        ('antecedentes_familiares', '0001_initial'),
        ('clasificacion_peso', '0001_initial'),
        ('comida_diaria', '0001_initial'),
        ('condiciones_medicas', '0001_initial'),
        ('consumo_comida_rapida', '0001_initial'),
        ('consumo_medicamentos', '0001_initial'),
        ('estres_ansiedad', '0001_initial'),
        ('personas', '0002_personas_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='actividades_fisicas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='actividades_fisicas.actividades_fisicas'),
        ),
        migrations.AddField(
            model_name='personas',
            name='antecedentes_familiares',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='antecedentes_familiares.antecedentes_familiares'),
        ),
        migrations.AddField(
            model_name='personas',
            name='comida_diaria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comida_diaria.comida_diaria'),
        ),
        migrations.AddField(
            model_name='personas',
            name='condiciones_medicas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='condiciones_medicas.condiciones_medicas'),
        ),
        migrations.AddField(
            model_name='personas',
            name='consumo_comida_rapida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='consumo_comida_rapida.consumo_comida_rapida'),
        ),
        migrations.AddField(
            model_name='personas',
            name='consumo_medicamentos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='consumo_medicamentos.consumo_medicamentos'),
        ),
        migrations.AddField(
            model_name='personas',
            name='estres_ansiedad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estres_ansiedad.estres_ansiedad'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='clasificacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clasificacion_peso.clasificacion'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='genero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='genero_personas', to='clasificacion_peso.clasificacion'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='imc',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
