# Generated by Django 5.1.1 on 2025-04-13 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades_fisicas', '0002_actividadesfisicas'),
        ('antecedentes_familiares', '0002_alter_antecedentes_familiares_options_and_more'),
        ('clasificacion_peso', '0002_alter_clasificacion_options_and_more'),
        ('comida_diaria', '0002_alter_comida_diaria_options_and_more'),
        ('condiciones_medicas', '0002_alter_condiciones_medicas_options_and_more'),
        ('consumo_comida_rapida', '0002_alter_consumo_comida_rapida_options_and_more'),
        ('consumo_medicamentos', '0002_alter_consumo_medicamentos_options_and_more'),
        ('estres_ansiedad', '0002_alter_estres_ansiedad_options_and_more'),
        ('personas', '0003_personas_actividades_fisicas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personas',
            options={'verbose_name': 'DATOS DE PERSONAS', 'verbose_name_plural': 'DATOS DE PERSONAS'},
        ),
        migrations.AlterField(
            model_name='personas',
            name='actividades_fisicas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='actividades_fisicas.actividadesfisicas', verbose_name='Actividades físicas'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='antecedentes_familiares',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='antecedentes_familiares.antecedentes_familiares', verbose_name='Antecedentes familiares'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='clasificacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clasificacion_peso.clasificacion', verbose_name='Clasificación de peso'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='comida_diaria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comida_diaria.comida_diaria', verbose_name='Comida diaria'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='condiciones_medicas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='condiciones_medicas.condiciones_medicas', verbose_name='Condiciones médicas'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='consumo_comida_rapida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='consumo_comida_rapida.consumo_comida_rapida', verbose_name='Consumo de comida rápida'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='consumo_medicamentos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='consumo_medicamentos.consumo_medicamentos', verbose_name='Consumo de medicamentos'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='edad',
            field=models.IntegerField(verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='estatura',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Estatura'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='estres_ansiedad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estres_ansiedad.estres_ansiedad', verbose_name='Estrés y ansiedad'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='genero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='genero_personas', to='clasificacion_peso.clasificacion', verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='imc',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='IMC'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='nombre_completo',
            field=models.CharField(max_length=255, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso'),
        ),
    ]
