# Generated by Django 5.1.1 on 2025-04-13 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genero', '0003_alter_genero_options'),
        ('personas', '0004_alter_personas_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='genero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='genero.genero', verbose_name='Género'),
        ),
    ]
