# Generated by Django 5.1.1 on 2025-04-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_alter_personas_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='imc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='IMC'),
        ),
    ]
